name: build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -i {0}
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ format('{0}-pip-{1}', runner.os, hashFiles('dev-requirements.txt', 'requirements.txt')) }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        make setup
    - name: test
      run: |
        coverage run -m pytest tests -vv
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
